/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Briefings: () => import('#controllers/briefings_controller'),
  Internal: () => import('#controllers/internal_controller'),
  Landing: () => import('#controllers/landing_controller'),
  Seo: () => import('#controllers/seo_controller'),
}
